# default inspect template
Step:
  widgets:
  - type: text
    instanceProp: status
    label: Status
  - type: text
    instanceProp: start
    label: Start
  - type: text
    instanceProp: end
    label: End
